version: '3'
services:
  app:
    container_name: lostAndFoundApi
    restart: always
    build: .
    command: npm run dev
    env_file: .env
    environment:
      - NODE_ENV=development
      - DB_USER_DEV=$DB_USER_DEV
      - DB_PASSWORD_DEV=$DB_PASSWORD_DEV
      - DB_HOST_DEV=mongo
      - DB_PORT_DEV=$DB_PORT_DEV
      - DB_NAME_DEV=$DB_NAME_DEV
    ports:
      - '3000:3000'
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
